language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - python -m ioutracker.src.HelpersTests
  - python -m ioutracker.src.IOUTrackerTests
  - python -m ioutracker.metrics.MOTMetricsTests